// @ts-expect-error Generated by the OpenNext build.
import handler from "./.open-next/worker.js";
import type { ExecutionContext } from "@cloudflare/workers-types";
import type { WakiEnv } from "./lib/cloudflare";

export { AttendeeVideoStream } from "./cloudflare/attendee-video-stream";

const worker = {
  async fetch(request: Request, env: WakiEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname === "/api/attendee/video") {
      if (request.headers.get("Upgrade")?.toLowerCase() !== "websocket") {
        return new Response("Expected a WebSocket upgrade.", { status: 426 });
      }
      if (!env.ATTENDEE_VIDEO_STREAM_TOKEN || url.searchParams.get("token") !== env.ATTENDEE_VIDEO_STREAM_TOKEN) {
        return new Response("Unauthorized.", { status: 401 });
      }

      const stream = env.ATTENDEE_VIDEO_STREAM.get(env.ATTENDEE_VIDEO_STREAM.idFromName("attendee-video"));
      return stream.fetch(request as never) as unknown as Response;
    }

    return handler.fetch(request, env, ctx);
  },
};

export default worker;
